apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: hydrated-meter-events
  labels:
    strimzi.io/cluster: iot-cluster
spec:
  partitions: 10
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
