apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: parking-finder-app
    app.kubernetes.io/component: parking-finder-app
    app.kubernetes.io/instance: parking-finder-app
  name: parking-finder-app
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: parking-finder-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: services/parking-finder-app
    git:
      uri: https://github.com/RedHat-Middleware-Workshops/rhtr-2020-api-mgmt-kafka-workshop
      ref: 2022-refresh
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:14-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: H1sM5ow3ksddUthma4xD
    type: GitHub
  - generic:
      secret: FvmRciZTtLegSfT0wpZW
    type: Generic
  - type: ConfigChange
  - imageChange:
    type: ImageChange
